"""add dish_categories dishes dish_images tables

Revision ID: 068e2411d8ad
Revises: d7119ae3dff4
Create Date: 2026-01-14 02:05:26.132078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '068e2411d8ad'
down_revision: Union[str, Sequence[str], None] = 'd7119ae3dff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_categories',
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='主キー（UUID）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='カテゴリ名'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='表示順序'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='削除日時（論理削除）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dishes',
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='主キー（UUID）'),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='ユーザーID'),
    sa.Column('category_id', mysql.CHAR(length=36), nullable=True, comment='カテゴリID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='料理名'),
    sa.Column('cooked_at', sa.Date(), nullable=False, comment='作った日'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='削除日時（論理削除）'),
    sa.ForeignKeyConstraint(['category_id'], ['dish_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dishes_user_cooked', 'dishes', ['user_id', 'cooked_at'], unique=False)
    op.create_index('idx_dishes_user_deleted', 'dishes', ['user_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_dishes_category_id'), 'dishes', ['category_id'], unique=False)
    op.create_index(op.f('ix_dishes_user_id'), 'dishes', ['user_id'], unique=False)
    op.create_table('dish_images',
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='主キー（UUID）'),
    sa.Column('dish_id', mysql.CHAR(length=36), nullable=False, comment='料理ID'),
    sa.Column('image_key', sa.String(length=200), nullable=False, comment='S3オブジェクトキー'),
    sa.Column('display_order', mysql.TINYINT(), nullable=False, comment='表示順序（1-3）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_images_dish_id'), 'dish_images', ['dish_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dish_images_dish_id'), table_name='dish_images')
    op.drop_table('dish_images')
    op.drop_index(op.f('ix_dishes_user_id'), table_name='dishes')
    op.drop_index(op.f('ix_dishes_category_id'), table_name='dishes')
    op.drop_index('idx_dishes_user_deleted', table_name='dishes')
    op.drop_index('idx_dishes_user_cooked', table_name='dishes')
    op.drop_table('dishes')
    op.drop_table('dish_categories')
    # ### end Alembic commands ###
