"""create users table

Revision ID: b1999fd52766
Revises: 
Create Date: 2025-12-23 00:46:01.588084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1999fd52766'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='主キー（UUID）'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='表示名（ニックネーム）'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='メールアドレス（ログインID）'),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True, comment='メール確認完了日時'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='ハッシュ化されたパスワード'),
    sa.Column('status', sa.Enum('active', 'provisional', 'banned', name='userstatus'), nullable=False, comment='ステータス'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最終ログイン日時'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新日時'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='削除日時（論理削除）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
