"""create refresh_tokens table

Revision ID: d7119ae3dff4
Revises: b1999fd52766
Create Date: 2025-12-31 09:37:23.441770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7119ae3dff4'
down_revision: Union[str, Sequence[str], None] = 'b1999fd52766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.CHAR(length=36), nullable=False, comment='主キー（UUID）'),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='ユーザーID'),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='トークンハッシュ（SHA-256）'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='有効期限'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='無効化日時'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='作成日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
